/**
 * NINJA AIRS Basketball Stats V21 - Google Apps Script
 * このコードをスプレッドシートの「拡張機能 > Apps Script」へ貼り付けてください。
 */
const SHEETS={SETTINGS:'設定',PLAYERS:'選手名簿',OPPONENTS:'対戦相手',GAMES:'試合一覧',DATA:'試合データ',CAREER:'通算スタッツ'};
const STAT_KEYS=['twoMade','twoMiss','threeMade','threeMiss','ftMade','ftMiss','oreb','dreb','assist','steal','turnover','foul'];

function doGet(e){return jsonOut(handle_((e&&e.parameter&&e.parameter.action)||'loadAll',{}));}
function doPost(e){try{const body=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');return jsonOut(handle_(body.action||'',body));}catch(err){return jsonOut({ok:false,error:String(err.stack||err)});}}
function jsonOut(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);}
function handle_(action,p){setup_();if(action==='setup')return {ok:true};if(action==='loadAll')return loadAll_();if(action==='savePlayers')return savePlayers_(p.players||[]);if(action==='saveGame')return saveGame_(p.game,p.players||[]);throw new Error('Unknown action: '+action);}

function setup_(){const ss=SpreadsheetApp.getActive();ensure_(SHEETS.SETTINGS,['項目','値']);ensure_(SHEETS.PLAYERS,['ID','カテゴリー','背番号','氏名','在籍','更新日時']);ensure_(SHEETS.OPPONENTS,['カテゴリー','チーム名','対戦数','最終対戦日']);ensure_(SHEETS.GAMES,['試合ID','日付','カテゴリー','対戦相手','自得点','相手得点','勝敗','状態','出場人数','保存日時','試合シート']);ensure_(SHEETS.DATA,['試合ID','JSON','更新日時']);ensure_(SHEETS.CAREER,['カテゴリー','背番号','選手名','試合数','平均得点','2P%','3P%','FT%','平均OR','平均DR','平均REB','平均AST','平均STL','平均TO','平均PF']);const sh=ss.getSheetByName(SHEETS.SETTINGS);if(sh.getLastRow()<2)sh.getRange(2,1,4,2).setValues([['アプリ名','NINJA AIRS Basketball Stats'],['バージョン','21'],['タイムゾーン','Asia/Tokyo'],['最終更新',new Date()]]);}
function ensure_(name,headers){const ss=SpreadsheetApp.getActive();let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0)sh.getRange(1,1,1,headers.length).setValues([headers]);sh.setFrozenRows(1);sh.getRange(1,1,1,headers.length).setFontWeight('bold').setBackground('#1557e8').setFontColor('#ffffff');return sh;}
function loadAll_(){const psh=SpreadsheetApp.getActive().getSheetByName(SHEETS.PLAYERS),dsh=SpreadsheetApp.getActive().getSheetByName(SHEETS.DATA);const players=psh.getLastRow()<2?[]:psh.getRange(2,1,psh.getLastRow()-1,6).getValues().filter(r=>r[0]).map(r=>({id:String(r[0]),group:String(r[1]),number:String(r[2]),name:String(r[3]),active:r[4]===true||String(r[4]).toUpperCase()==='TRUE'}));const games=dsh.getLastRow()<2?[]:dsh.getRange(2,1,dsh.getLastRow()-1,3).getValues().filter(r=>r[0]&&r[1]).map(r=>{try{return JSON.parse(r[1])}catch(e){return null}}).filter(Boolean).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||'')));return {ok:true,players,games,serverTime:new Date().toISOString()};}
function savePlayers_(players){const sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.PLAYERS);if(sh.getLastRow()>1)sh.getRange(2,1,sh.getLastRow()-1,6).clearContent();if(players.length)sh.getRange(2,1,players.length,6).setValues(players.map(p=>[p.id,p.group,p.number,p.name,!!p.active,new Date()]));sh.autoResizeColumns(1,6);return {ok:true,count:players.length};}
function saveGame_(g,players){if(!g||!g.id)throw new Error('試合データがありません');if(players.length)savePlayers_(players);upsertData_(g);upsertGameList_(g);rebuildOpponents_();writeGameSheet_(g,players);rebuildCareer_();return {ok:true,gameId:g.id};}
function upsertData_(g){const sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.DATA),row=findRow_(sh,String(g.id),1),vals=[g.id,JSON.stringify(g),new Date()];if(row)sh.getRange(row,1,1,3).setValues([vals]);else sh.appendRow(vals);}
function upsertGameList_(g){const sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.GAMES),row=findRow_(sh,String(g.id),1),sheetName=gameSheetName_(g),result=Number(g.ourScore)>Number(g.oppScore)?'勝':Number(g.ourScore)<Number(g.oppScore)?'負':'分',vals=[g.id,g.date,g.category,g.opponent,g.ourScore||0,g.oppScore||0,result,g.status,g.appearances?g.appearances.length:0,new Date(),sheetName];if(row)sh.getRange(row,1,1,vals.length).setValues([vals]);else sh.appendRow(vals);sh.autoResizeColumns(1,vals.length);}
function rebuildOpponents_(){
  const ss=SpreadsheetApp.getActive(),sh=ss.getSheetByName(SHEETS.OPPONENTS),all=loadAll_().games;
  const map=new Map();
  all.forEach(g=>{
    const category=String(g.category||''),name=String(g.opponent||'').trim();
    if(!category||!name)return;
    const key=category+'|||'+name,prev=map.get(key)||{category,name,count:0,last:''};
    prev.count+=1;
    if(String(g.date||'')>prev.last)prev.last=String(g.date||'');
    map.set(key,prev);
  });
  if(sh.getLastRow()>1)sh.getRange(2,1,sh.getLastRow()-1,4).clearContent();
  const rows=[...map.values()].sort((a,b)=>a.category.localeCompare(b.category,'ja')||a.name.localeCompare(b.name,'ja')).map(x=>[x.category,x.name,x.count,x.last]);
  if(rows.length)sh.getRange(2,1,rows.length,4).setValues(rows);
  sh.autoResizeColumns(1,4);
}
function writeGameSheet_(g,players){const ss=SpreadsheetApp.getActive(),name=gameSheetName_(g);let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);sh.clear();sh.getRange('A1:D4').setValues([['試合日',g.date,'カテゴリー',g.category],['対戦相手',g.opponent,'状態',g.status],['NINJA',g.ourScore||0,g.opponent,g.oppScore||0],['保存日時',new Date(),'試合ID',g.id]]);sh.getRange('A1:D4').setFontWeight('bold');let row=6;row=writeTeam_(sh,row,'自チーム',players.filter(p=>(g.appearances||[]).includes(p.id)),g.stats||{},true);row+=2;writeTeam_(sh,row,'相手チーム',(g.oppPlayers||[]).filter(p=>(g.oppAppearances||[]).includes(p.id)),g.oppStats||{},false);sh.setFrozenRows(5);sh.autoResizeColumns(1,16);}
function writeTeam_(sh,row,title,list,stats,isOur){const headers=['背番号','選手名','PTS','2P成功','2P試投','2P%','3P成功','3P試投','3P%','FT成功','FT試投','FT%','OR','DR','AST','STL','TO','PF'];sh.getRange(row,1).setValue(title).setFontWeight('bold').setFontSize(14).setBackground(isOur?'#dbe9ff':'#ffe1e3');row++;sh.getRange(row,1,1,headers.length).setValues([headers]).setFontWeight('bold').setBackground('#061a33').setFontColor('#ffffff');row++;const vals=list.map(p=>{const s=stats[p.id]||{},tm=s.twoMade||0,ta=tm+(s.twoMiss||0),thm=s.threeMade||0,tha=thm+(s.threeMiss||0),fm=s.ftMade||0,fa=fm+(s.ftMiss||0),pts=tm*2+thm*3+fm;return [p.number,isOur?p.name:'',pts,tm,ta,ta?tm/ta:'',thm,tha,tha?thm/tha:'',fm,fa,fa?fm/fa:'',s.oreb||0,s.dreb||0,s.assist||0,s.steal||0,s.turnover||0,s.foul||0]});if(vals.length){sh.getRange(row,1,vals.length,headers.length).setValues(vals);sh.getRange(row,6,vals.length,1).setNumberFormat('0.0%');sh.getRange(row,9,vals.length,1).setNumberFormat('0.0%');sh.getRange(row,12,vals.length,1).setNumberFormat('0.0%');}return row+vals.length;}
function rebuildCareer_(){const all=loadAll_(),players=all.players,games=all.games.filter(g=>g.status==='finished'),sh=SpreadsheetApp.getActive().getSheetByName(SHEETS.CAREER);if(sh.getLastRow()>1)sh.getRange(2,1,sh.getLastRow()-1,15).clearContent();const rows=players.map(p=>{const gs=games.filter(g=>(g.appearances||[]).includes(p.id)),n=gs.length,sum=k=>gs.reduce((a,g)=>a+Number(((g.stats||{})[p.id]||{})[k]||0),0),tm=sum('twoMade'),tmiss=sum('twoMiss'),thm=sum('threeMade'),thmiss=sum('threeMiss'),fm=sum('ftMade'),fmiss=sum('ftMiss'),pts=tm*2+thm*3+fm,or=sum('oreb'),dr=sum('dreb');return [p.group,p.number,p.name,n,n?pts/n:'',tm+tmiss?tm/(tm+tmiss):'',thm+thmiss?thm/(thm+thmiss):'',fm+fmiss?fm/(fm+fmiss):'',n?or/n:'',n?dr/n:'',n?(or+dr)/n:'',n?sum('assist')/n:'',n?sum('steal')/n:'',n?sum('turnover')/n:'',n?sum('foul')/n:'']});if(rows.length){sh.getRange(2,1,rows.length,15).setValues(rows);sh.getRange(2,6,rows.length,3).setNumberFormat('0.0%');sh.getRange(2,5,rows.length,1).setNumberFormat('0.0');sh.getRange(2,9,rows.length,7).setNumberFormat('0.0');}sh.autoResizeColumns(1,15);}
function findRow_(sh,value,col){if(sh.getLastRow()<2)return 0;const vals=sh.getRange(2,col,sh.getLastRow()-1,1).getDisplayValues().flat();const i=vals.indexOf(value);return i<0?0:i+2;}
function gameSheetName_(g){const suffix=String(g.id||'').replace(/[^a-zA-Z0-9]/g,'').slice(-6);const base=String(g.date||'').replace(/-/g,'')+'_'+String(g.category||'')+'_vs_'+String(g.opponent||'相手')+'_'+suffix;return base.replace(/[\\\/\?\*\[\]:]/g,'').slice(0,99);}
